# Generated by Django 3.2.7 on 2021-09-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_images', '0002_ocr_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocr',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
